import React, { useEffect } from "react";

const TermsOfService = () => {
     // Scroll to top when this page is loaded
      useEffect(() => {
        window.scrollTo(0, 0);
      }, []);
  return (
    <div className="bg-white py-16">
      <div className="max-w-5xl mx-auto p-6 md:p-12 text-gray-800 leading-relaxed shadow-lg rounded-xl">
        <h1 className="text-4xl font-bold mb-8 text-[#63559A] text-center tracking-wide">
          Terms of Service
        </h1>

        <p className="text-sm text-gray-500 mb-8 text-center">
          Effective Date: October 4, 2024
        </p>

        <p className="mb-6">
          Thank you for choosing <strong>KOLCO COMMERCE PRIVATE LIMITED</strong> ("GoGetWell AI", "Go Get Well", "we," "our," or "us"). 
          These Terms of Service ("Terms") govern your use of our AI-powered medical tourism platform, including our software applications, websites, and any other services we offer (collectively, "Services"). By accessing or using our Services, you agree to be bound by these Terms.
        </p>

        {/* Section 1 */}
        <section className="mb-10 p-6 bg-white shadow-sm rounded-lg">
          <h2 className="text-2xl font-semibold mb-4 text-[#63559A]">1. Registration and Access</h2>
          <h3 className="text-xl font-medium mb-2">Minimum Age:</h3>
          <p className="mb-4">
            You must be at least 18 years old to use our Services. If you are under 18, your use of the Services must be supervised by a parent or legal guardian who consents to these Terms on your behalf.
          </p>

          <h3 className="text-xl font-medium mb-2">Account Registration:</h3>
          <p>
            You must provide accurate and complete information to register for an account. For healthcare facilitators, this includes valid business information. You are responsible for all activities under your account and must maintain the confidentiality of your credentials.
          </p>
        </section>

        {/* Section 2 */}
        <section className="mb-10 p-6 bg-white shadow-sm rounded-lg">
          <h2 className="text-2xl font-semibold mb-4 text-[#63559A]">2. Use of Our Services</h2>
          <h3 className="text-xl font-medium mb-2">Permitted Use:</h3>
          <p className="mb-4">
            Subject to compliance with these Terms, you may access and use our Services for medical tourism purposes. You must comply with all applicable laws, including the Information Technology Act, 2000, and any other relevant regulations related to healthcare and tourism.
          </p>

          <h3 className="text-xl font-medium mb-2">Prohibited Activities:</h3>
          <ul className="list-disc ml-6 space-y-2">
            <li>Infringe, misappropriate, or violate anyone's rights, including patient privacy rights.</li>
            <li>Modify, copy, lease, sell, or distribute any part of our Services.</li>
            <li>Attempt to reverse-engineer or discover the source code of our AI-powered Services.</li>
            <li>Automatically extract data without our permission.</li>
            <li>Use output generated by the Services for any purpose that could have a legal or material impact on a third party, especially in a medical context.</li>
            <li>Interfere with the functionality of our medical tourism platform.</li>
          </ul>
        </section>

        {/* Section 3 */}
        <section className="mb-10 p-6 bg-white shadow-sm rounded-lg">
          <h2 className="text-2xl font-semibold mb-4 text-[#63559A]">3. Intellectual Property Rights</h2>
          <p>
            We and our affiliates own all rights, title, and interest in the Services, including any content, software, and other intellectual property related to our AI-powered medical tourism solutions.
          </p>
        </section>

        {/* Section 4 */}
        <section className="mb-10 p-6 bg-white shadow-sm rounded-lg">
          <h2 className="text-2xl font-semibold mb-4 text-[#63559A]">4. Content</h2>

          <h3 className="text-xl font-medium mb-2">User Content:</h3>
          <p className="mb-4">
            You may provide input to the Services ("Input"), including medical information, and receive output ("Output") such as treatment recommendations. You retain ownership of the Input you provide, and we assign to you all rights in the Output generated by the Services, subject to these Terms.
          </p>

          <h3 className="text-xl font-medium mb-2">Our Use of Content:</h3>
          <p>
            We may use your Input and Output to develop, improve, and provide our medical tourism Services. If you do not want us to use your content for these purposes, please contact us.
          </p>
        </section>

        {/* Section 5 */}
        <section className="mb-10 p-6 bg-white shadow-sm rounded-lg">
          <h2 className="text-2xl font-semibold mb-4 text-[#63559A]">5. Disclaimer of Warranties</h2>
          <p>
            OUR SERVICES ARE PROVIDED "AS IS." WHILE WE STRIVE FOR ACCURACY IN OUR AI-POWERED RECOMMENDATIONS, WE DISCLAIM ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
          </p>
        </section>

        {/* Section 6 */}
        <section className="mb-10 p-6 bg-white shadow-sm rounded-lg">
          <h2 className="text-2xl font-semibold mb-4 text-[#63559A]">6. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, we are not liable for any indirect, incidental, consequential, or punitive damages, or loss of profits, revenue, data, or business opportunities resulting from your use of our Services.
          </p>
        </section>

        {/* Section 7 */}
        <section className="mb-10 p-6 bg-white shadow-sm rounded-lg">
          <h2 className="text-2xl font-semibold mb-4 text-[#63559A]">7. Changes to These Terms</h2>
          <p>
            We may modify these Terms from time to time. If we make material changes, we will notify you by updating the effective date at the top of these Terms.
          </p>
        </section>

        {/* Section 8 */}
        <section className="p-6 bg-white shadow-sm rounded-lg">
          <h2 className="text-2xl font-semibold mb-4 text-[#63559A]">8. Contact Us</h2>
          <p>
            If you have any questions about these Terms or our medical tourism services, please contact us at 
            <a href="mailto:hello@gogetwell.ai" className="text-[#63559A] underline ml-1">hello@gogetwell.ai</a>.
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsOfService;
